### ISSUE TITLE
Valor mínimo na parcela

### ISSUE THREAD

**Issue by daluzluiz** [claudiosmweb/woocommerce-moip#11]
Claudio, gostaria de parabeniza-lo pelo plugin. Obrigado.

Tenho uma dúvida/sugestão. Seria possivel adicionar um valor mínimo para pagamentos parcelados? Exemplo: Uma parcela mínima de R$50,00. Sei que é possivel selecionar o número mínimo e máximo de parcela, mas não um valor mínimo. OBrigado

**Comment by claudiosmweb** [comment]
Fechando em favor de #14
