### ISSUE TITLE
variações do produto em tabela

### ISSUE THREAD

**Issue by wagnerjaccoud** [claudiosmweb/woocommerce-moip#17]
Olá cládio, estou atrás de algo que faça parecido com esse vídeo https://vimeo.com/104905602, o que achei mais próximo foi o bulk-variations, porém não fica tão simplificado como este do vídeo. Gostaria da sua ajuda.

**Comment by claudiosmweb** [comment]
Não entendi a ligação disso com este plugin aqui.
